routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('https://mail.zoho.com/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });


Route::get('/', 'Front\HomeController@index');
Route::get('quem-somos', 'Front\AboutController@index');
Route::get('servicos', 'Front\ServicesController@index');
Route::get('servicos/{slugServico}', 'Front\ServicesController@show');
Route::get('blogs', 'Front\BlogsController@index');
Route::get('blogs/{slugBlog}', 'Front\BlogsController@show');
Route::get('/depoimentos', 'Front\ReviewController@index');
Route::post('/depoimentos-create', 'Front\ReviewController@store');
Route::get('/contato', 'Front\ContactController@index');
Route::get('/reservas', 'Front\ReservationController@index');

Route::get('/banco-reservas', 'Front\ReservationController@view')->name('bank.index');
Route::get('/banco-reservas/{name}', 'Front\ReservationController@show')->name('bank.show');
Route::get('/banco-reservas/{name}/info/{reservation}', 'Front\ReservationController@info')->name('bank.info');

Route::prefix('services')->namespace('Services')->group(function() {
    Route::post('send-mail', 'MailController@sendContact');
    Route::prefix('newsletter')->group(function() {
        Route::post('/', 'MailController@subscribe');
        Route::get('confirm/{code}', 'MailController@confirmSubscribe');
    });
    Route::apiResource('pre-registration', 'PreRegistrationController');
    Route::get('reservations', 'ReservationsController@index');
    Route::delete('reservations/{reservation}', 'ReservationsController@destroy');
    Route::match(['patch','put'], 'reservations', 'ReservationsController@update');

    Route::post('bank-reservations/{reservation}/interest', 'BankReservationController@interest');
    Route::delete('bank-reservations/interest/{reservation_interest}', 'BankReservationController@destroy');
    Route::match(['patch','put'],'bank-reservations/interest/{reservation_interest}', 'BankReservationController@update');
});


Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');
	Route::resource('about', 'Admin\AboutController');
	Route::resource('services', 'Admin\ServicesController');
	Route::resource('blogs', 'Admin\BlogsController');
	Route::resource('sliders', 'Admin\SlidersController');
	Route::resource('reviews', 'Admin\ReviewsController');
	Route::resource('clients', 'Admin\ClientsController');
	Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    Route::view('pre-registrations', 'admin.pre-registrations.index')->name('pre-registrations.index');
    Route::get('reservations', 'Admin\ReservationsController@index')->name('reservations.index');
    Route::match(['GET', 'POST'], 'reservations/new', 'Admin\ReservationsController@insert')->name('reservations.insert');
    Route::match(['GET', 'PUT'],'reservations/{reservation}', 'Admin\ReservationsController@viewOrUpdate')->name('reservations.viewOrUpdate');
    Route::get('reservations/{id}/ficha', 'Admin\ReservationsController@create')->name('reservations.create');
    Route::post('reservations/{id}/ficha', 'Admin\ReservationsController@store')->name('reservations.store');
});

Auth::routes();

app/Models/About.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $fillable = [
    	'page_description',
    	'page_image',
    	'box_vision_title',
    	'box_vision_description',
    	'box_mission_title',
    	'box_mission_description',
    	'box_quality_one_title',
    	'box_quality_one_description',
    	'box_quality_two_title',
    	'box_quality_two_description',
    	'box_quality_three_title',
    	'box_quality_three_description'
    ];
}

app/Http/Controllers/Admin/AboutController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\About\StoreRequest;
//use App\Http\Requests\Admin\About\UpdateRequest;

use App\Models\About;

class AboutController extends Controller
{
    /**
     * Armazena uma nova instancia do model About
     *
     * @var \App\About
     */
    private $abouts;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
      $this->abouts = app(About::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $about = About::firstOrFail();
      return view('admin.abouts.index', compact('about'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {

      $about = $this->abouts->firstOrFail();

      if(!$about) {
        session()->flash('messages.error', ['Quem Somos não existe!']);
        return redirect()->route('about.index');
      }

      if(!Input::hasFile('page_image') == null){
        $foto_antiga = $about->page_image;

        if(Storage::has($foto_antiga)){
          Storage::delete($foto_antiga);
        }

        $file = $request->file('page_image');

        if(!$file->isValid()) {
          abort(400, 'Imagem não encontrada ou não é válida');
        }

        $arquivo = $file->store('quem-somos');
        $about->page_image = $arquivo;
      }
      // testa depois      
      // $about->fill( $request->all() ); // o laravel ignora os elementos não atribuiveis

      $about->page_description = $request->page_description;
      $about->box_vision_title = $request->box_vision_title;
      $about->box_vision_description = $request->box_vision_description;
      $about->box_mission_title = $request->box_mission_title;
      $about->box_mission_description = $request->box_mission_description;
      $about->box_quality_one_title = $request->box_quality_one_title;
      $about->box_quality_one_description = $request->box_quality_one_description;
      $about->box_quality_two_title = $request->box_quality_two_title;
      $about->box_quality_two_description = $request->box_quality_two_description;
      $about->box_quality_three_title = $request->box_quality_three_title;
      $about->box_quality_three_description = $request->box_quality_three_description;
      $about->save();

      session()->flash('messages.success', ['Quem Somos alterado com sucesso!']);
      return redirect()->route('about.index');

    }

  }

app/Http/Controllers/Front/AboutController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    public function index()
    {
    	return view('front.about');
    }
}

resources/views/admin/abouts/index.blade.php
@extends('admin.base')
@section('title', 'Editar Quem Somos')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  @include('elements.messages')

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title')
         </div>

         <div class="panel-body">

          <form action="{{ route('about.store')}}" enctype="multipart/form-data" method="POST">
            {!! csrf_field() !!}

            <div class="row">
              <div class="col-xs-12 col-md-8">

                <div class="form-group @if ($errors->has('page_description')) has-error @endif">
                  <label for="page_description" class="form-label">Descrição da Página</label>
                  <textarea rows="18" class="form-control textarea" id="page_description" name="page_description" value="{{ $abouts->page_description ?? old('page_description') }}" placeholder="Descrição da Página" autofocus>{{ $abouts->page_description ?? old('page_description') }}</textarea>
                  @if ($errors->has('page_description'))
                  <span class="help-block">
                    <strong>{{ $errors->first('page_description') }}</strong>
                  </span>
                  @endif
                </div><!-- form-group -->

              </div>
              <div class="col-xs-12 col-md-4">
                <div class="form-group">
                  <label for="page_image" class="form-label">Imagem da Página</label>
                  <img src="/storage/{{ $abouts->page_image ?? old('page_image') }}" alt="Quem Somos" class="img-thumbnail">
                  <input type="file" class="form-control" id="page_image" name="page_image" value="{{ $abouts->page_image ?? old('page_image') }}">
                </div>

                <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
              </div>
            </div>

            <hr>

            <div class="row">
              <div class="col-xs-12 col-md-5 col-md-offset-1">
                <h4>Box  <b>Nossa Visão</b></h4>

                <div class="form-group @if ($errors->has('box_vision_title')) has-error @endif">
                  <label for="box_vision_title" class="form-label">Título</label>
                  <input type="text" class="form-control" id="box_vision_title" name="box_vision_title" value="{{ $abouts->box_vision_title ?? old('box_vision_title') }}" placeholder="Título da Box">
                  @if ($errors->has('box_vision_title'))
                  <span class="help-block">
                    <strong>{{ $errors->first('box_vision_title') }}</strong>
                  </span>
                  @endif
                </div><!-- form-group -->

                <div class="form-group @if ($errors->has('box_vision_description')) has-error @endif">
                  <label for="box_vision_description" class="form-label">Descrição</label>
                  <textarea rows="4" class="form-control" id="box_vision_description" name="box_vision_description" value="{{ $abouts->box_vision_description ?? old('box_vision_description') }}" placeholder="Descrição da Página">{{ $abouts->box_vision_description ?? old('box_vision_description') }}</textarea>
                  @if ($errors->has('box_vision_description'))
                  <span class="help-block">
                    <strong>{{ $errors->first('box_vision_description') }}</strong>
                  </span>
                  @endif
                </div><!-- form-group -->

              </div><!-- col-md-5 -->
              <div class="col-xs-12 col-md-5">
                <h4>Box  <b>Nossa Missão</b></h4>

                <div class="form-group @if ($errors->has('box_mission_title')) has-error @endif">
                  <label for="box_mission_title" class="form-label">Título</label>
                  <input type="text" class="form-control" id="box_mission_title" name="box_mission_title" value="{{ $abouts->box_mission_title ?? old('box_mission_title') }}" placeholder="Título da Box">
                  @if ($errors->has('box_mission_title'))
                  <span class="help-block">
                    <strong>{{ $errors->first('box_mission_title') }}</strong>
                  </span>
                  @endif
                </div><!-- form-group -->

                <div class="form-group @if ($errors->has('box_mission_description')) has-error @endif">
                  <label for="box_mission_description" class="form-label">Descrição</label>
                  <textarea rows="4" class="form-control" id="box_mission_description" name="box_mission_description" value="{{ $abouts->box_mission_description ?? old('box_mission_description') }}" placeholder="Descrição da Página">{{ $abouts->box_mission_description ?? old('box_mission_description') }}</textarea>
                  @if ($errors->has('box_mission_description'))
                  <span class="help-block">
                    <strong>{{ $errors->first('box_mission_description') }}</strong>
                  </span>
                  @endif
                </div><!-- form-group -->

              </div><!-- col-md-5 -->
            </div><!-- row -->

            <hr>

            <div class="row">
              <div class="col-xs-12 col-md-10 col-md-offset-1">
                <h4>Box  <b>Nossa Qualidades</b></h4>

                <div class="row">
                  <div class="col-xs-12 col-md-4">
                    <div class="form-group @if ($errors->has('box_quality_one_title')) has-error @endif">
                      <label for="box_quality_one_title" class="form-label">Título</label>
                      <input type="text" class="form-control" id="box_quality_one_title" name="box_quality_one_title" value="{{ $abouts->box_quality_one_title ?? old('box_quality_one_title') }}" placeholder="Título da Box">
                      @if ($errors->has('box_quality_one_title'))
                      <span class="help-block">
                        <strong>{{ $errors->first('box_quality_one_title') }}</strong>
                      </span>
                      @endif
                    </div><!-- form-group -->

                    <div class="form-group @if ($errors->has('box_quality_one_description')) has-error @endif">
                      <label for="box_quality_one_description" class="form-label">Descrição</label>
                      <textarea rows="6" class="form-control" id="box_quality_one_description" name="box_quality_one_description" value="{{ $abouts->box_quality_one_description ?? old('box_quality_one_description') }}" placeholder="Descrição da Página">{{ $abouts->box_quality_one_description ?? old('box_quality_one_description') }}</textarea>
                      @if ($errors->has('box_quality_one_description'))
                      <span class="help-block">
                        <strong>{{ $errors->first('box_quality_one_description') }}</strong>
                      </span>
                      @endif
                    </div><!-- form-group -->
                  </div><!-- col-md-4 -->

                  <div class="col-xs-12 col-md-4">
                    <div class="form-group @if ($errors->has('box_quality_two_title')) has-error @endif">
                      <label for="box_quality_two_title" class="form-label">Título</label>
                      <input type="text" class="form-control" id="box_quality_two_title" name="box_quality_two_title" value="{{ $abouts->box_quality_two_title ?? old('box_quality_two_title') }}" placeholder="Título da Box">
                      @if ($errors->has('box_quality_two_title'))
                      <span class="help-block">
                        <strong>{{ $errors->first('box_quality_two_title') }}</strong>
                      </span>
                      @endif
                    </div><!-- form-group -->

                    <div class="form-group @if ($errors->has('box_quality_two_description')) has-error @endif">
                      <label for="box_quality_two_description" class="form-label">Descrição</label>
                      <textarea rows="6" class="form-control" id="box_quality_two_description" name="box_quality_two_description" value="{{ $abouts->box_quality_two_description ?? old('box_quality_two_description') }}" placeholder="Descrição da Página">{{ $abouts->box_quality_two_description ?? old('box_quality_two_description') }}</textarea>
                      @if ($errors->has('box_quality_two_description'))
                      <span class="help-block">
                        <strong>{{ $errors->first('box_quality_two_description') }}</strong>
                      </span>
                      @endif
                    </div><!-- form-group -->
                  </div><!-- col-md-4 -->

                  <div class="col-xs-12 col-md-4">
                    <div class="form-group @if ($errors->has('box_quality_three_title')) has-error @endif">
                      <label for="box_quality_three_title" class="form-label">Título</label>
                      <input type="text" class="form-control" id="box_quality_three_title" name="box_quality_three_title" value="{{ $abouts->box_quality_three_title ?? old('box_quality_three_title') }}" placeholder="Título da Box">
                      @if ($errors->has('box_quality_three_title'))
                      <span class="help-block">
                        <strong>{{ $errors->first('box_quality_three_title') }}</strong>
                      </span>
                      @endif
                    </div><!-- form-group -->

                    <div class="form-group @if ($errors->has('box_quality_three_description')) has-error @endif">
                      <label for="box_quality_three_description" class="form-label">Descrição</label>
                      <textarea rows="6" class="form-control" id="box_quality_three_description" name="box_quality_three_description" value="{{ $abouts->box_quality_three_description ?? old('box_quality_three_description') }}" placeholder="Descrição da Página">{{ $abouts->box_quality_three_description ?? old('box_quality_three_description') }}</textarea>
                      @if ($errors->has('box_quality_three_description'))
                      <span class="help-block">
                        <strong>{{ $errors->first('box_quality_three_description') }}</strong>
                      </span>
                      @endif
                    </div><!-- form-group -->
                  </div><!-- col-md-4 -->

                </div><!-- row -->
                

              </div><!-- col-md-11 -->

              <div class="row">
                <div class="col-md-6">
                  <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
                  <a href="{{ url('/dashboard') }}" class="btn btn-sm btn-warning"><i class="fa fa-reply"></i> Cancelar</a>
                </div><!-- col-md-6 -->
              </div>

            </form>

          </div><!-- panel-body -->


        </div><!-- panel-default -->
      </div><!-- col-md-12 -->


    </div><!-- row -->
  </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')

@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
/* BOOTSTRAP WYSIHTML5 */
$('.textarea').wysihtml5();

/* SUMMERNOTE*/
$(document).ready(function() {
  $('.summernote').summernote();
});
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
$('input[name="title"]').stringToSlug({
  setEvents: 'keyup keydown blur',
  getPut: 'input[name="url"]',
  space: '-',
  replace: '/\s?\([^\)]*\)/gi',
AND: 'e'
});
</script>
@endsection